# DB_HOST=<your-host>
# DB_NAME=<your-db-name>
# DB_USER=<your-db-username>
# DB_PASS=<your-db-password>

version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=creditdb 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ykpostdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - creditapproval
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py makemigrations core &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    working_dir: "/app"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=creditdb
      - DB_USER=postgres
      - DB_PASS=ykpostdb
    depends_on:
      - db
    networks:
      - creditapproval

volumes:
  postgres_data:

networks:
  creditapproval:
    driver: bridge