# Generated by Django 3.2.25 on 2025-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('monthly_income', models.IntegerField()),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('approved_limit', models.IntegerField()),
            ],
        ),
    ]
